# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

production:
  secret_key_base: c8657ab26dbbbea184fdbec5c1ca105b9c209239402bf2ed33a44c75f2de4dc3e3e8d84ac03d5b47c42d013489008aa3717abae96fd95d0afa16b978e427a3f0
  json_web_token_secret: ddd5336f5426a07606d538a6a108530f4be24f4a9adf3a96d8a3f0348833676e153e9132ad11dd4b0483d2e463d970a2b59ae26ec844a7f95bae8930c78ac088

#production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
#  json_web_token_secret: <%= ENV["JWT_SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  json_web_token_secret: <%= ENV["JWT_SECRET_KEY_BASE"] %>
